### ISSUE TITLE
Independent assessment report of Corretto

### ISSUE THREAD

**Issue by Dominique-D** [awsdocs/amazon-corretto-8-user-guide#1]
Hello,

As I would like to add Corretto to our product catalog to make it available to the users. Before adding it, I am requested to provide an independent assessment report of Corretto. Is it the right place to request it? If not where should I request it?

A typical report format is:
•	Title page
•	Table of Content
•	Assessor background
•	Executive summary
•	Details of vulnerabilities with rating

Dominique

**Comment by jschwarzwalder** [comment]
This repository contains the source documentation for Amazon Corretto from AWS. Any assessment report from us, would not be independent. 

Are you an AWS Support Customer? If so, you can reach out to Customer Support where we can better assist you and work to understand what you need. 

Thank you for reaching out and using Corretto.
