### ISSUE TITLE
Which version supports TLS 1.3

### ISSUE THREAD

**Issue by nitin-garg** [awsdocs/amazon-corretto-8-user-guide#2]
Hi,

Please let me know which corretto version supports TLS 1.3?

Thanks,
Nitin Garg

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
