### ISSUE TITLE
Live documentation is not linked to this repository

### ISSUE THREAD

**Issue by ttres** [awsdocs/amazon-corretto-8-user-guide#4]
I can see [Docker section](https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/docker-install.html), on Corretto 8 User Guide, doesn't reflect internal documentation [here](https://github.com/awsdocs/amazon-corretto-8-user-guide/blob/master/doc_source/docker-install.md).

*Expectation*
When I click on live documentation button _Edit this page on GitHub_ I want to see current Markdown code.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
