### ISSUE TITLE
Using ECR section is pointing to wrong link

### ISSUE THREAD

**Issue by ttres** [awsdocs/amazon-corretto-8-user-guide#5]
*Using the Corretto ECR instance* documentation section is pointing to deprecated blog post.

**Expectation**
Authentication to Corretto ECR registry should use `aws ecr get-login-password` command, available [here](https://docs.aws.amazon.com/AmazonECR/latest/userguide/registry_auth.html#registry-auth-token).

**Current**
Authentication to Corretto ECR registry still use `aws ecr get-login` deprecated command.

**Comment by joshbean** [comment]
Closing this issue or pull request in advance of archiving this repo. For more information about the decision to archive this repo (and others in the 'awsdocs' org), see [the announcement on the AWS News Blog](https://aws.amazon.com/blogs/aws/retiring-the-aws-documentation-on-github/).
